### ISSUE TITLE
 Index/report/dashboard level isolation at the UI level for different users in Kibana

### ISSUE THREAD

**Issue by SvetA95** [starrlingo/aws-mt-es-kibana-proxy#1]
Could you give em a tip how it's supposed to work? I managed to set up the whole thing. But all of my indexes are available for all of the users and I don't want that.

Any help would be much appreciated. Thanks.

**Comment by starrlingo** [comment]
This proxy only works with AWS Elasticsearch Service. When you access this proxy in HTTP, it will authenticate the user first (you can also customize this part). Afterwards, the proxy try to assume IAM role to get one hour permission to access Kibana. The IAM role for the login tenant define the exact permission and UI level isolation stuff. You can take a look at the README page for the IAM policy template.

**Comment by SvetA95** [comment]
Hi, sorry for not asking my question correctly the first time. I have the whole proxy working, everything from the README is done. My exact question is after a user logs in for the first time and attempts to create his indexes, is there a way to isolate the indexes available in the creation list? I don't want a user to have access to all of the indexes.

Thanks

**Comment by starrlingo** [comment]
Yes, it can be done by setting your IAM role of desired login tenant. Take my IAM role policy as an example, I can only manage the **api-starrlingo** index in the Kibana.  When I try to add some other index, Kibana will show the index does not exist.
~~~
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "es:*",
            "Resource": [
                "arn:aws:es:ap-northeast-1:<my accountID>:domain/<my esDomain>/api-starrlingo",
                "arn:aws:es:ap-northeast-1:<my accountID>:domain/<my esDomain>/api-starrlingo/*",
                "arn:aws:es:ap-northeast-1:<my accountID>:domain/<my esDomain>/",
                "arn:aws:es:ap-northeast-1:<my accountID>:domain/<my esDomain>/favicon.ico",
                "arn:aws:es:ap-northeast-1:<my accountID>:domain/<my esDomain>/_plugin/kibana",
                "arn:aws:es:ap-northeast-1:<my accountID>:domain/<my esDomain>/_plugin/kibana/*",
                "arn:aws:es:ap-northeast-1:<my accountID>:domain/<my esDomain>/_nodes",
                "arn:aws:es:ap-northeast-1:<my accountID>:domain/<my esDomain>/_nodes/*",
                "arn:aws:es:ap-northeast-1:<my accountID>:domain/<my esDomain>/.kibana-4",
                "arn:aws:es:ap-northeast-1:<my accountID>:domain/<my esDomain>/.kibana-4-starrlingo",
                "arn:aws:es:ap-northeast-1:<my accountID>:domain/api-aap-1-byoc-ga/.kibana-4-starrlingo/*"
            ]
        }
    ]
}
~~~
Moreover, all the index saved by user in the side bar, dashboards and reports are stored in 
.kibana-4-< tenantID >. Therefore, only the user with right tenantID can watch them.

**Comment by SvetA95** [comment]
Ok. Thanks for that. One last question. Could you give me an example of your domain policy as well please? Are you using IAM or Resource policy? Because I tried something similar to your Role policy but got always got the, access,  Anonymus user,  error and this is an issue of the domain policy i think. Currently my domain policy is IAM and IP based, and as a resource I just use the arn:domain/*. Your help is much appreciated. Thanks.

**Comment by starrlingo** [comment]
There are two policies need to be settled down. Here is the sample policy as following.
1. IAM role policy for your login tenant

~~~
Role Name: aws-mt-kibana-starrlingo
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "es:*",
            "Resource": [
                "arn:aws:es:ap-northeast-1:<my accountID>:domain/<my esDomain>/api-starrlingo",
                "arn:aws:es:ap-northeast-1:<my accountID>:domain/<my esDomain>/api-starrlingo/*",
                "arn:aws:es:ap-northeast-1:<my accountID>:domain/<my esDomain>/",
                "arn:aws:es:ap-northeast-1:<my accountID>:domain/<my esDomain>/favicon.ico",
                "arn:aws:es:ap-northeast-1:<my accountID>:domain/<my esDomain>/_plugin/kibana",
                "arn:aws:es:ap-northeast-1:<my accountID>:domain/<my esDomain>/_plugin/kibana/*",
                "arn:aws:es:ap-northeast-1:<my accountID>:domain/<my esDomain>/_nodes",
                "arn:aws:es:ap-northeast-1:<my accountID>:domain/<my esDomain>/_nodes/*",
                "arn:aws:es:ap-northeast-1:<my accountID>:domain/<my esDomain>/.kibana-4",
                "arn:aws:es:ap-northeast-1:<my accountID>:domain/<my esDomain>/.kibana-4-starrlingo",
                "arn:aws:es:ap-northeast-1:<my accountID>:domain/api-aap-1-byoc-ga/.kibana-4-starrlingo/*"
            ]
        }
    ]
}
~~~
2. Policy in AWS Elasticsearch domain
~~~
  {
    "Effect": "Allow",
    "Principal": {
       "AWS": "arn:aws:iam::<account id>:role/aws-mt-kibana-starrlingo"
    },
    "Action": "es:*",
    "Resource": "arn:aws:es:<region>:<account id>:domain/<my es domain name>/"
  }
~~~

**Comment by SvetA95** [comment]
Thanks, you helped me a lot. :)

**Comment by SvetA95** [comment]
Hi, after applying all the policies I get the following error: Kibana: Waiting for Kibana index ".kibana-4" to come online failed - Do you have any ideas? Thanks.

**Comment by SvetA95** [comment]
The following is my error:

XML Parsing Error: not well-formed
Location: http://127.0.0.1:5601/_plugin/kibana/config?_b=7562
Line Number 1, Column 1:  config:1:1
"INFO: 2017-02-08T15:27:34Z
  Adding connection to http://127.0.0.1:5601/

"  index.js:84892:5
bootstrapindex.js:45946
es checkindex.js:45946
config initindex.js:45946
complete in 943.51ms  index.js:45942:11
checkEsVersionindex.js:45946
complete in 812.33ms  index.js:45942:11
kibana index checkindex.js:45946
complete in 790.12ms  index.js:45942:11
kibana index migrationindex.js:45946
Error: Waiting for Kibana index ".kibana-4" to come online failed
ErrorAbstract@http://127.0.0.1:5601/_plugin/kibana/index.js?_b=7562:84002:19
StatusCodeError@http://127.0.0.1:5601/_plugin/kibana/index.js?_b=7562:84151:5
respond@http://127.0.0.1:5601/_plugin/kibana/index.js?_b=7562:85344:15
checkRespForFailure@http://127.0.0.1:5601/_plugin/kibana/index.js?_b=7562:85312:7
[24]</AngularConnector.prototype.request/<@http://127.0.0.1:5601/_plugin/kibana/index.js?_b=7562:83950:7
qFactory/defer/deferred.promise.then/wrappedErrback@http://127.0.0.1:5601/_plugin/kibana/index.js?_b=7562:20902:31
qFactory/defer/deferred.promise.then/wrappedErrback@http://127.0.0.1:5601/_plugin/kibana/index.js?_b=7562:20902:31
qFactory/defer/deferred.promise.then/wrappedErrback@http://127.0.0.1:5601/_plugin/kibana/index.js?_b=7562:20902:31
qFactory/createInternalRejectedPromise/<.then/<@http://127.0.0.1:5601/_plugin/kibana/index.js?_b=7562:21035:29
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://127.0.0.1:5601/_plugin/kibana/index.js?_b=7562:22022:16
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://127.0.0.1:5601/_plugin/kibana/index.js?_b=7562:21834:15
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://127.0.0.1:5601/_plugin/kibana/index.js?_b=7562:22126:13
done@http://127.0.0.1:5601/_plugin/kibana/index.js?_b=7562:17661:34
completeRequest@http://127.0.0.1:5601/_plugin/kibana/index.js?_b=7562:17875:7
createHttpBackend/</xhr.onreadystatechange@http://127.0.0.1:5601/_plugin/kibana/index.js?_b=7562:17814:11
  index.js:19337:18

I'm not sure where the problem is and can't find anything close to it to compare. My guess is that I'm missing something in the Role policy, I need an exception for something else but I don't know what it is. If you have any ideas, it would be much appreciated. Thanks

**Comment by SvetA95** [comment]
Figured it out. Another necessary line in the policy is:
 "arn:aws:es:ap-northeast-1:<my accountID>:domain/<my esDomain>/_cluster/health/*",

**Comment by starrlingo** [comment]
Any question and PR are welcome.

**Comment by SvetA95** [comment]
Thank you again for the help. Great work! :+1:
