### ISSUE TITLE
400 bad request when accessing Kibana

### ISSUE THREAD

**Issue by Photon89** [starrlingo/aws-mt-es-kibana-proxy#2]
I am trying to use aws-mt-es-kibana-proxy and worked through the readme successfully. When running aws-mt-es-kibana-proxy, 

`node index.js https://<working aws url>.es.amazonaws.com -n pp -a exampleLocalAuth`

I get a 400 error in the browser and the following output and log: https://pastebin.com/6W7S0jB2

Looking at the output, for some reason `baseUrl` inside the `req` variable is empty though a working AWS URL is provided in the execution command and the authentication at AWS and assuming a role also seems to work out.

Not sure if this is a bug or I am doing something wrong, so thanks for any input!

**Comment by avallen** [comment]
I found this is due to specifying the endpoint with the protocol scheme, invoke it with just the hostname instead, else the protocol will end up in the forwarded request's Host header, which is then rejected by the ELB fronting the cluster.

**Comment by Photon89** [comment]
I'm not into this stuff any more (was dealing with it as part of an internship) so I cannot check if the solution works but I guess it does, so I'm closing the report.
